FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY weather-server/ weather-server/
RUN CGO_ENABLED=0 go build -o /weather-server ./weather-server/

FROM alpine:3.19
COPY --from=builder /weather-server /weather-server
EXPOSE 8888
CMD ["/weather-server"]
