FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY evil-server/ evil-server/
RUN CGO_ENABLED=0 go build -o /evil-server ./evil-server/

FROM alpine:3.19
COPY --from=builder /evil-server /evil-server
EXPOSE 9999
CMD ["/evil-server"]
