#!/usr/bin/env python3
"""Generate deterministic tool fixtures for the CE-Manager security demo.

Six fixtures, each sized to ~18-22K o200k tokens (72-88 KB), containing:
  - lots of noise (similar-looking records, compliance text, audit blurbs,
    policy reminders) so that the answer is genuinely hard to spot in
    bulk, and
  - one clearly-relevant entry or field — the "signal" that the agent
    must extract before calling the next tool.

Run:
    python3 scripts/fixtures_gen.py

Outputs:
    ce-demo-agent/fixtures/*.json

Seeded RNG → byte-identical outputs across runs.
"""
from __future__ import annotations

import json
import random
from pathlib import Path

try:
    import tiktoken
    ENC = tiktoken.get_encoding("o200k_base")
    def count_tokens(s: str) -> int:
        return len(ENC.encode(s))
except Exception:  # noqa: BLE001
    ENC = None
    def count_tokens(s: str) -> int:
        return len(s) // 4


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ce-demo-agent" / "fixtures"
OUT.mkdir(parents=True, exist_ok=True)

# Smaller fixtures — ~44 KB ≈ ~11 K o200k tokens. With the expanded chain
# (3× get_session_events + 2× lookup_ip_reputation + 2× get_file_access_log),
# Q1's cumulative context crosses 70% around the 7th call and crosses 100%
# around the 11th in CE_MODE=off, producing a dramatic mid-investigation
# overflow. CE modes compact well below the limit.
TARGET_CHARS = 44_000
TARGET_CHARS_LARGE = 52_000


POLICY_BLURB = (
    "Reminder: this output is governed by the Acme Information Sharing Policy "
    "rev. 2026-03-14. Handling ANY data contained herein requires compliance "
    "with SEC 3.4 (data at rest), SEC 3.5 (data in transit), and the Acme "
    "incident-response runbook section 12. Do not forward to non-authorized "
    "systems. Retention: 180 days. Classification: internal-sensitive."
)
AUDIT_BLURB = (
    "Audit trail: record generated by platform-telemetry v4.7.1, snapshot "
    "window aligned to UTC midnight boundaries. Data lineage: raw events are "
    "ingested from the edge collectors, normalized in the curation pipeline, "
    "and materialized here via the analytics warehouse view."
)


# ---------- helpers ----------

def pad(rng: random.Random, target_chars: int, build_one, *, relevant=None, relevant_position="middle"):
    """Append records from build_one(i) until the serialized payload hits the target."""
    records = []
    if relevant is not None and relevant_position == "start":
        records.append(relevant)
    i = 0
    while True:
        s = json.dumps(records, separators=(",", ":"))
        if len(s) >= target_chars:
            break
        records.append(build_one(i))
        i += 1
        if i == 10**5:
            break  # safety
    if relevant is not None and relevant_position != "start":
        # Put the signal somewhere in the middle so the LLM has to find it.
        mid = int(len(records) * 0.62)
        records.insert(mid, relevant)
    return records


def hexid(rng: random.Random, n: int) -> str:
    return "".join(rng.choices("0123456789abcdef", k=n))


def ts(rng: random.Random, day: str, hour_range: tuple[int, int] = (0, 23)) -> str:
    h = rng.randint(*hour_range)
    m = rng.randint(0, 59)
    s = rng.randint(0, 59)
    return f"{day}T{h:02d}:{m:02d}:{s:02d}Z"


# ---------- fixture 1: get_user_profile ----------

def build_user_profile() -> dict:
    rng = random.Random(1)

    def session(i: int) -> dict:
        day = rng.choice(["2026-04-24","2026-04-25","2026-04-28","2026-04-30",
                          "2026-05-01","2026-05-02","2026-05-03","2026-05-04",
                          "2026-05-05"])
        return {
            "id": f"s-{hexid(rng, 12)}",
            "started_at": ts(rng, day),
            "ended_at": ts(rng, day),
            "ip_country": rng.choice(["US","US","US","GB","US","DE","US"]),
            "device_fingerprint": hexid(rng, 32),
            "user_agent": rng.choice([
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15",
                "Mozilla/5.0 (Windows NT 10.0; Win64) Gecko/20100101 Firefox/127",
                "Mozilla/5.0 (X11; Linux x86_64) Chrome/131.0",
            ]),
            "app_scopes": rng.sample(
                ["hr:read","calendar:rw","vault:read","email:send","mail:read","files:read","files:write","chat:rw","reports:read","finance:read"],
                k=rng.randint(3, 7),
            ),
        }

    # Three candidate morning sessions on 2026-05-06 — only one is the real
    # attacker session. The agent must call get_session_events on each to
    # work out which. Decoy sessions are internal/benign but look suspicious
    # at the profile-listing level.
    signal_session = {
        "id": "s-morning-042",
        "started_at": "2026-05-06T09:14:07Z",
        "ended_at": "2026-05-06T09:42:11Z",
        "ip_country": "RU",
        "device_fingerprint": "f00dba" + "0" * 26,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; rv:120.0) Gecko/20100101 Firefox/120.0",
        "app_scopes": ["files:read","vault:read","email:send","reports:read","finance:read"],
    }
    aux_session_1 = {
        "id": "s-morning-aux1",
        "started_at": "2026-05-06T07:48:22Z",
        "ended_at": "2026-05-06T08:05:11Z",
        "ip_country": "US",
        "device_fingerprint": "abbe1d" + "0" * 26,
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15",
        "app_scopes": ["calendar:rw","mail:read","chat:rw"],
    }
    aux_session_2 = {
        "id": "s-morning-aux2",
        "started_at": "2026-05-06T08:31:09Z",
        "ended_at": "2026-05-06T09:02:47Z",
        "ip_country": "US",
        "device_fingerprint": "c0ff33" + "0" * 26,
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/131.0",
        "app_scopes": ["reports:read","finance:read","files:read"],
    }

    recent_sessions = pad(rng, 3_200, session, relevant=signal_session)
    # Insert the two aux sessions at other positions so the three candidates
    # are spread across the list.
    recent_sessions.insert(int(len(recent_sessions) * 0.30), aux_session_1)
    recent_sessions.insert(int(len(recent_sessions) * 0.50), aux_session_2)

    profile = {
        "user_id": "U-9284",
        "email": "alice.chen@acme.corp",
        "display_name": "Alice Chen",
        "status": "active",
        "employee_id": "E-04228",
        "manager_user_id": "U-1102",
        "cost_center": "CC-22981",
        "title": "Senior Financial Analyst",
        "department": "Finance / Board Reporting",
        "office": "SF-HQ-04-117",
        "joined_at": "2022-06-14",
        "last_password_reset": "2026-02-19",
        "mfa_status": {
            "enrolled": True,
            "factors": ["totp", "backup_codes"],
            "last_used": "2026-05-03T18:41:12Z",
            "backup_codes_remaining": 7,
        },
        "compliance_training": [
            {"course": "Phishing 101", "completed_at": "2026-03-11", "score": 0.94},
            {"course": "Handling Board Data", "completed_at": "2026-04-02", "score": 1.00},
            {"course": "Export Controls", "completed_at": "2026-04-02", "score": 0.89},
            {"course": "Data Retention", "completed_at": "2026-04-17", "score": 0.92},
        ],
        "recent_session_ids": recent_sessions,
        "group_memberships": [
            "finance-board-reporting","financial-analysts-sf","all-hands",
            "okta-standard-workforce","board-meeting-prep-2026","m365-e5",
        ],
        "access_reviews": [
            {"review_id": f"ar-{i}", "reviewed_on": "2026-04-01", "decision": "approved"}
            for i in range(12)
        ],
        "preferred_communication_channels": ["email", "slack"],
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }

    # Bulk out with benign noise so the relevant session list isn't the biggest
    # thing in the payload. CE-Manager's masker should decide most of this is
    # throwaway and keep only the sessions list + the core IDs.
    rng2 = random.Random(11)
    def note(i: int) -> dict:
        return {
            "kind": rng2.choice(["hr-note","self-attestation","peer-feedback","ooo-record","training-receipt"]),
            "timestamp": ts(rng2, rng2.choice(["2026-02-10","2026-02-17","2026-03-05","2026-03-18","2026-04-04"])),
            "author_user_id": f"U-{rng2.randint(1000,9999)}",
            "body": rng2.choice([
                "Quarterly check-in completed on time. No concerns raised.",
                "Requested access to reports:read for Q2 close support.",
                "Attended board-reporting syncs weekly; no escalations.",
                "OOO from 2026-04-12 to 2026-04-19; return date confirmed.",
                "Completed mandatory compliance refreshers ahead of schedule.",
            ]),
        }
    profile["hr_notes"] = pad(rng2, 20_000, note)

    rng3 = random.Random(12)
    def policy_ack(i: int) -> dict:
        return {
            "policy_id": f"POL-{rng3.randint(100, 999)}-r{rng3.randint(1, 12)}",
            "title": rng3.choice([
                "Handling Externally Shared Financial Data",
                "Incident Reporting Obligations",
                "Use of Generative AI in Workflows",
                "Preferred Messaging Apps",
                "Hardware Token Rotation Policy",
                "Travel Laptop Checkout Procedure",
            ]),
            "ack_at": ts(rng3, rng3.choice(["2026-02-01","2026-02-14","2026-03-01","2026-03-20"])),
            "rev_ack_at": ts(rng3, "2026-04-05"),
            "summary": rng3.choice([
                "Read in full; opted into reminder cadence.",
                "Acknowledged; no deviations requested.",
                "Cross-references the SOX-24 handbook; no overrides.",
                "Department rollup confirmed; see attachments for lineage.",
            ]),
        }
    profile["policy_acknowledgements"] = pad(rng3, 22_000, policy_ack)

    return profile


# ---------- fixture 2: get_session_events ----------

def build_session_events() -> dict:
    rng = random.Random(2)

    def event(i: int) -> dict:
        et = rng.choices(
            ["page_view","api_call","keystroke_burst","heartbeat","cache_hit","telemetry_flush"],
            weights=[3,4,1,2,2,1],
        )[0]
        return {
            "type": et,
            "ts": ts(rng, "2026-05-06", hour_range=(9, 9)),
            "path": rng.choice([
                "/dashboard","/reports","/reports/q3","/vault","/calendar",
                "/board/packets","/settings/security","/files/drive/root",
                "/search?q=approved","/notifications","/admin/audit",
            ]),
            "latency_ms": rng.randint(5, 900),
            "http_status": rng.choice([200,200,200,200,304,401,404]),
            "bytes_out": rng.randint(100, 98_000),
            "client_error_code": None,
            "notes": rng.choice([
                "Refreshed navigation panel.",
                "Cache invalidated on policy rotation.",
                "Keystroke burst aggregated from 0.5s window.",
                "Heartbeat ping; no user activity.",
                "Telemetry flush on page hide.",
            ]),
        }

    # The signal: one login event with mfa_method=bypassed, ip 203.0.113.42.
    # NOTE: user_agent is on the login event itself, so the agent has to pick
    # the right login row before it can extract the browser string.
    signal_login = {
        "type": "login",
        "ts": "2026-05-06T09:19:42Z",
        "ip_address": "203.0.113.42",
        "mfa_method": "bypassed",
        "auth_provider": "okta",
        "result": "success",
        "risk_engine_score": 0.91,
        "failure_reason": None,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; rv:120.0) Gecko/20100101 Firefox/120.0",
        "notes": "Login succeeded after three failed TOTP attempts; MFA was then bypassed via an unexpired password-reset token.",
    }

    # Decoys — plausibly-suspicious near-matches. Neither is mfa_method=bypassed
    # and neither is from 203.0.113.42. The model has to distinguish these
    # from the real signal on its own.
    decoy_early_login = {
        "type": "login",
        "ts": "2026-05-06T09:03:11Z",
        "ip_address": "198.51.100.7",
        "mfa_method": "totp",
        "auth_provider": "okta",
        "result": "success",
        "risk_engine_score": 0.12,
        "failure_reason": None,
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15",
        "notes": "Normal morning login from the corporate VPN egress.",
    }
    decoy_failed_login = {
        "type": "login",
        "ts": "2026-05-06T09:11:58Z",
        "ip_address": "192.0.2.99",
        "mfa_method": "sms",
        "auth_provider": "okta",
        "result": "failure",
        "risk_engine_score": 0.66,
        "failure_reason": "sms_code_expired",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) Chrome/131.0",
        "notes": "Expired SMS — user retried on TOTP successfully (see next login).",
    }

    events = pad(rng, 66_000, event, relevant=signal_login)
    # Drop the two decoy logins at ~20% and ~40% positions, well before the
    # real signal (~62%), so the scanner hits decoys first.
    events.insert(int(len(events) * 0.21), decoy_early_login)
    events.insert(int(len(events) * 0.41), decoy_failed_login)

    return {
        "session_id": "s-morning-042",
        "user_id": "U-9284",
        "query_echo": {"session_id": "s-morning-042"},
        "events": events,
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- fixture 3: lookup_ip_reputation ----------

def build_ip_reputation() -> dict:
    rng = random.Random(3)

    def old_sighting(i: int) -> dict:
        return {
            "ts": ts(rng, rng.choice(["2025-11-04","2025-12-18","2026-01-21",
                                      "2026-02-03","2026-03-07","2026-04-12"])),
            "source": rng.choice(["spamhaus","abuseipdb","teamcymru","greynoise","internal-honeypot"]),
            "category": rng.choice(["scanner","bruteforce","phishing-infra","credstuffing","proxy"]),
            "evidence_id": hexid(rng, 16),
            "severity": rng.choice(["low","medium","medium","high","high","critical"]),
            "confidence": round(rng.uniform(0.5, 0.99), 3),
            "tags": rng.sample(
                ["ssh","http","smb","rdp","smtp","apt","tor-exit","residential-vpn"],
                k=rng.randint(1, 4),
            ),
        }

    sightings = pad(rng, 50_000, old_sighting)

    def whois_hist(i: int) -> dict:
        return {
            "change_at": ts(rng, "2024-01-15"),
            "field": rng.choice(["registrar","nameservers","abuse_email","org_name"]),
            "from": rng.choice(["PrivacyGuardians LLC","NetReg GmbH","InetCloud OU"]),
            "to": rng.choice(["ShadowHost Ltd","Fast-Flux Networks","HostPolyp OU"]),
        }

    whois = pad(rng, 12_000, whois_hist)

    return {
        "ip": "203.0.113.42",
        "asn": 64512,
        "asn_org": "EXAMPLE-AS (reserved)",
        "country": "RU",
        "city": "Moscow",
        "hosting_type": "datacenter",
        "risk_score": 97,
        "risk_tier": "critical",
        "first_seen": "2025-08-21",
        "threat_lists": [
            "spamhaus-drop",
            "abuse-ch-sslbl",
            "internal-honeypot-priority",
            "APT-GROUP-BEARFANG",
        ],
        "linked_campaigns": [
            {"campaign": "BEARFANG-2026-H1", "confidence": 0.93},
            {"campaign": "ShipyardCred-2025-Q4", "confidence": 0.71},
        ],
        "observed_attack_types": ["initial-access","credential-access","collection","exfiltration"],
        "whois_history": whois,
        "recent_sightings": sightings,
        "abuse_contacts": ["abuse@shadowhost.example"],
        "analyst_commentary": (
            "IP is in the datacenter range advertised by ShadowHost Ltd (RU). "
            "Associated with APT-GROUP-BEARFANG staging infrastructure since 2025-08. "
            "Multiple vendors report credential stuffing, MFA-fatigue prompts, and "
            "post-exploit data exfiltration over HTTPS and SMTP. Block at perimeter."
        ),
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- fixture 4: get_file_access_log ----------

def build_file_access_log() -> dict:
    rng = random.Random(4)

    def access(i: int) -> dict:
        folders = ["/home/alice","/shared/finance","/shared/hr","/shared/board",
                   "/projects/close-q2","/projects/close-q3","/reports/monthly",
                   "/templates","/reference"]
        folder = rng.choice(folders)
        name = rng.choice([
            "notes.txt","draft.md","budget.xlsx","forecast.csv","agenda.docx",
            "minutes.docx","review.pdf","handoff.md","dashboard.png","schedule.ics",
        ])
        return {
            "ts": ts(rng, "2026-05-06", hour_range=(9, 9)),
            "action": rng.choices(["read","read","read","read","open","write","download"],
                                  weights=[3,3,3,3,1,1,1])[0],
            "path": f"{folder}/{name}",
            "bytes": rng.randint(64, 4_000_000),
            "device": rng.choice(["workstation-alice","mobile-alice","remote-desktop-office"]),
            "client_ip": rng.choice(["10.12.34.56","10.12.34.57","203.0.113.42"]),
            "audit_ref": hexid(rng, 16),
        }

    signal = {
        "ts": "2026-05-06T09:23:11Z",
        "action": "download",
        "path": "/financials/board/Q3-2026-preliminary.xlsx",
        "bytes": 2_441_472,
        "device": "remote-desktop-office",
        "client_ip": "203.0.113.42",
        "audit_ref": "rca-0000000000000001",
        "sensitivity": "board-confidential",
        "notes": "Full download of the preliminary Q3 financial close package, including revenue-by-segment tabs.",
    }

    # Near-miss decoys: a previously-approved board file (wrong filename, wrong
    # client_ip) and a Q2 file (wrong quarter). Both look board-ish at a glance.
    decoy_approved = {
        "ts": "2026-05-06T08:47:03Z",
        "action": "download",
        "path": "/financials/board/Q3-2026-approved.xlsx",
        "bytes": 1_824_301,
        "device": "workstation-alice",
        "client_ip": "10.12.34.56",
        "audit_ref": "rca-0000000000000010",
        "sensitivity": "board-confidential",
        "notes": "Previously-approved Q3 read-only copy, cached locally.",
    }
    decoy_q2 = {
        "ts": "2026-05-06T09:13:44Z",
        "action": "download",
        "path": "/financials/Q2-2026-final.xlsx",
        "bytes": 981_320,
        "device": "workstation-alice",
        "client_ip": "10.12.34.56",
        "audit_ref": "rca-0000000000000011",
        "sensitivity": "finance-confidential",
        "notes": "Q2 final — closed reporting period; read for reference only.",
    }

    files = pad(rng, 66_000, access, relevant=signal)
    files.insert(int(len(files) * 0.18), decoy_approved)
    files.insert(int(len(files) * 0.38), decoy_q2)

    return {
        "user_id": "U-9284",
        "query_echo": {
            "user_id": "U-9284",
            "start_ts": "2026-05-06T09:00:00Z",
            "end_ts": "2026-05-06T12:00:00Z",
        },
        "files": files,
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- fixture 5: get_data_exfil_attempts ----------

def build_data_exfil() -> dict:
    rng = random.Random(5)

    def outbound(i: int) -> dict:
        channel = rng.choice(["email","slack-dm","external-share","upload-dropbox","upload-box","upload-corp"])
        internal_recipients = [
            "peer.manager@acme.corp","finance-leads@acme.corp","board-prep@acme.corp",
            "alice.chen@acme.corp",
        ]
        external_recipients = [
            "tax-advisor@external-partner.example","auditor@kpmgexample.example",
            "counsel@lawfirm.example",
        ]
        dest = rng.choice(internal_recipients + external_recipients)
        return {
            "ts": ts(rng, "2026-05-06", hour_range=(9, 9)),
            "channel": channel,
            "destination": dest,
            "attachments": [{"name": rng.choice(["notes.pdf","meeting.ics","draft.docx"]),
                             "bytes": rng.randint(1024, 800_000),
                             "hash": hexid(rng, 64)}]
            if channel != "slack-dm" else [],
            "policy_decision": "allow",
            "scanners": {"dlp": "clean", "av": "clean"},
            "notes": rng.choice([
                "Standard internal distribution.",
                "Shared with external tax advisor — pre-approved partner.",
                "Cleared by DLP; matches monthly reporting workflow.",
                "Content fingerprint matched approved template.",
            ]),
        }

    signal = {
        "ts": "2026-05-06T09:27:03Z",
        "channel": "email",
        "destination": "attacker@malicious.example",
        "attachments": [{
            "name": "Q3-2026-preliminary.xlsx",
            "bytes": 2_441_472,
            "hash": "9a37e4b1c0fd6b5a" + "0" * 48,
        }],
        "policy_decision": "allow",
        "scanners": {"dlp": "bypass-flag", "av": "clean"},
        "notes": (
            "Outbound email to an external domain not on the approved-partners list. "
            "DLP engine was bypassed because an admin-scope API key was used to send "
            "via the transactional mail gateway instead of the enforced perimeter."
        ),
    }

    # Decoys: legitimate external emails carrying (harmless) board-adjacent
    # attachments. Both are to approved partners and clean on DLP/AV — they
    # exist to confuse a scanner that just greps for "external email + board".
    decoy_tax = {
        "ts": "2026-05-06T09:04:11Z",
        "channel": "email",
        "destination": "tax-advisor@external-partner.example",
        "attachments": [{
            "name": "Q3-board-agenda.pdf",
            "bytes": 514_229,
            "hash": hexid(rng, 64),
        }],
        "policy_decision": "allow",
        "scanners": {"dlp": "clean", "av": "clean"},
        "notes": "Standard advisor briefing — destination is on the approved-partners list.",
    }
    decoy_audit = {
        "ts": "2026-05-06T09:18:29Z",
        "channel": "email",
        "destination": "auditor@kpmgexample.example",
        "attachments": [{
            "name": "Q2-2026-signoff.pdf",
            "bytes": 401_003,
            "hash": hexid(rng, 64),
        }],
        "policy_decision": "allow",
        "scanners": {"dlp": "clean", "av": "clean"},
        "notes": "Q2 sign-off package for the external audit firm (approved partner).",
    }

    events = pad(rng, 66_000, outbound, relevant=signal)
    events.insert(int(len(events) * 0.22), decoy_tax)
    events.insert(int(len(events) * 0.48), decoy_audit)

    return {
        "user_id": "U-9284",
        "query_echo": {"user_id": "U-9284"},
        "events": events,
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- fixture 6: search_logins_by_ip ----------

def build_search_logins_by_ip() -> dict:
    rng = random.Random(6)

    def failed_login(i: int) -> dict:
        return {
            "ts": ts(rng, rng.choice(["2026-04-11","2026-04-16","2026-04-22",
                                      "2026-04-28","2026-05-02","2026-05-05"])),
            "user": rng.choice([
                "ivan.barnes@acme.corp","yuki.tanaka@acme.corp","frederik.ost@acme.corp",
                "marta.silva@acme.corp","huan.wu@acme.corp","niko.ovchinnikova@acme.corp",
            ]),
            "result": rng.choice(["failure","failure","failure","failure","failure","rate_limited"]),
            "failure_reason": rng.choice(["bad_password","mfa_timeout","account_locked","rate_limited"]),
            "mfa_method": rng.choice(["totp","push","sms","none"]),
            "risk_engine_score": round(rng.uniform(0.6, 0.99), 3),
            "client_ip": "203.0.113.42",
            "request_id": hexid(rng, 16),
        }

    signals = [
        {
            "ts": "2026-05-05T23:41:08Z",
            "user": "alice.chen@acme.corp",
            "result": "success",
            "failure_reason": None,
            "mfa_method": "bypassed",
            "risk_engine_score": 0.91,
            "client_ip": "203.0.113.42",
            "request_id": "rca-0000000000000002",
        },
        {
            "ts": "2026-05-06T04:14:17Z",
            "user": "bob.ryan@acme.corp",
            "result": "success",
            "failure_reason": None,
            "mfa_method": "bypassed",
            "risk_engine_score": 0.93,
            "client_ip": "203.0.113.42",
            "request_id": "rca-0000000000000003",
        },
        {
            "ts": "2026-05-06T07:51:04Z",
            "user": "carlos.liu@acme.corp",
            "result": "success",
            "failure_reason": None,
            "mfa_method": "bypassed",
            "risk_engine_score": 0.95,
            "client_ip": "203.0.113.42",
            "request_id": "rca-0000000000000004",
        },
    ]

    logins: list[dict] = []
    i = 0
    while True:
        logins.append(failed_login(i))
        i += 1
        s = json.dumps(logins, separators=(",", ":"))
        if len(s) >= 42_000:
            break
    # Drop the signals in different positions
    for pos, item in zip([int(len(logins)*0.3), int(len(logins)*0.55), int(len(logins)*0.78)], signals):
        logins.insert(pos, item)

    return {
        "ip": "203.0.113.42",
        "window": "30d",
        "query_echo": {"ip": "203.0.113.42", "window": "30d"},
        "logins": logins,
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- fixture 7: get_session_events_aux ----------
#
# Events fixture returned when the agent calls get_session_events on one of
# the aux morning sessions (s-morning-aux1 / s-morning-aux2). It contains
# benign activity (no mfa_method=="bypassed" login) so the chain correctly
# rules these candidates out.

def build_session_events_aux() -> dict:
    rng = random.Random(7)

    def event(i: int) -> dict:
        et = rng.choices(
            ["page_view","api_call","keystroke_burst","heartbeat","cache_hit","telemetry_flush"],
            weights=[3,4,1,2,2,1],
        )[0]
        return {
            "type": et,
            "ts": ts(rng, "2026-05-06", hour_range=(7, 9)),
            "path": rng.choice([
                "/dashboard","/reports","/calendar","/notifications","/admin/audit",
            ]),
            "latency_ms": rng.randint(5, 900),
            "http_status": rng.choice([200,200,200,200,304]),
            "bytes_out": rng.randint(100, 98_000),
            "client_error_code": None,
            "notes": rng.choice([
                "Routine morning activity.",
                "Cache invalidated on policy rotation.",
                "Heartbeat ping; no user activity.",
            ]),
        }

    benign_login = {
        "type": "login",
        "ts": "2026-05-06T07:48:22Z",
        "ip_address": "10.12.34.56",
        "mfa_method": "totp",
        "auth_provider": "okta",
        "result": "success",
        "risk_engine_score": 0.05,
        "failure_reason": None,
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15",
        "notes": "Normal login from the corporate VPN egress.",
    }

    events = pad(rng, 66_000, event, relevant=benign_login)

    return {
        "session_id": "s-morning-aux",
        "user_id": "U-9284",
        "query_echo": {"session_id": "s-morning-aux"},
        "events": events,
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- fixture 8: lookup_ip_reputation_benign ----------
#
# Returned when the agent looks up any IP that is NOT the real attacker.
# Keeps the chain honest (low risk, no threat-list membership) so the agent
# can confidently identify 203.0.113.42 as the real bad actor.

def build_ip_reputation_benign() -> dict:
    rng = random.Random(8)

    def sighting(i: int) -> dict:
        return {
            "ts": ts(rng, rng.choice(["2025-12-18","2026-02-03","2026-03-07","2026-04-12"])),
            "source": rng.choice(["greynoise","internal-honeypot"]),
            "category": "benign-scanner",
            "evidence_id": hexid(rng, 16),
            "severity": "low",
            "confidence": round(rng.uniform(0.3, 0.8), 3),
            "tags": ["monitoring"],
        }

    sightings = pad(rng, 50_000, sighting)

    return {
        "ip": "10.12.34.56",
        "asn": 65530,
        "asn_org": "ACME-CORP-INTERNAL",
        "country": "US",
        "city": "San Francisco",
        "hosting_type": "corporate-vpn",
        "risk_score": 4,
        "risk_tier": "benign",
        "first_seen": "2022-01-01",
        "threat_lists": [],
        "linked_campaigns": [],
        "observed_attack_types": [],
        "whois_history": [],
        "recent_sightings": sightings,
        "abuse_contacts": ["security@acme.corp"],
        "analyst_commentary": (
            "Corporate VPN egress — benign. No credential-stuffing, MFA-fatigue, "
            "or exfiltration patterns observed from this IP."
        ),
        "audit_blurb": AUDIT_BLURB,
        "policy": POLICY_BLURB,
    }


# ---------- main ----------

def dump(name: str, obj: dict) -> None:
    path = OUT / f"{name}.json"
    s = json.dumps(obj, separators=(",", ":"))
    path.write_text(s)
    tokens = count_tokens(s)
    print(f"  {name:<44s} {len(s):>7d} chars  ~{tokens:>6d} tokens")


def main() -> None:
    # Wipe the old SRE fixtures so we don't ship stale ones.
    for p in OUT.glob("*.json"):
        p.unlink()

    print("Generating CE-demo security fixtures:")
    dump("get_user_profile_alice",                 build_user_profile())
    dump("get_session_events_morning",             build_session_events())
    dump("get_session_events_aux",                 build_session_events_aux())
    dump("lookup_ip_reputation_203_0_113_42",      build_ip_reputation())
    dump("lookup_ip_reputation_benign",            build_ip_reputation_benign())
    dump("get_file_access_log_alice_morning",      build_file_access_log())
    dump("get_data_exfil_attempts_alice",          build_data_exfil())
    dump("search_logins_by_ip_203_0_113_42",       build_search_logins_by_ip())
    print("Done.")


if __name__ == "__main__":
    main()
